### ISSUE TITLE
Suggestion: Can we add a shrink button at the end of the expansion

### ISSUE THREAD

**Issue by sunjun2009311** [EchoPuda/fold_warp#1]
Can I add a shrink button at the end of the expansion and set the maximum number of displayed rows?
Hope to have these extensions

**Comment by EchoPuda** [comment]
@sunjun2009311 最大行数原本就支持的，'maxLine'
```dart
FoldWrap({
    Key? key,
    required this.children,
    this.foldWidget,
    this.foldLine = 0,
    this.maxLine = 0,
    this.isFold = false,
    this.spacing = 0,
    this.runSpacing = 0,
    this.lineMaxLength = 0,
    required this.extentHeight,
    this.onCallLineNum,
    this.foldWidgetInEnd = false,
  })
```
展开后的收起按钮的话，其实可以自己添加，展开后在组件之后显示就好了，一般来说都是这样的设计。
```dart
Column(
    children: [
        FoldWrap(...),
        !isFold ? FoldButton() : Container(),
    ]
)
```

假如是跟随在内容的最后面，你可以在children的末尾加上按钮，然后未展开时为Container()或其他，展开就是对应的按钮。

或者是更复杂的场景，你可以fork下来自行调整？我封装一个组件的话一般不会去考虑太复杂的场景，毕竟是一个通用的组件

**Comment by sunjun2009311** [comment]
感谢回复，差不多就是在绘制的末尾加上折叠的组件即可，这个小问题算是解决了。
![Screenre1](https://github.com/EchoPuda/fold_wrap/assets/3069184/248bd33a-923d-4141-8a61-ad1a03e03d41)
